FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY src/api/AccessControl.Api/ ./AccessControl.Api/
RUN dotnet restore ./AccessControl.Api/AccessControl.Api.csproj
RUN dotnet publish ./AccessControl.Api/AccessControl.Api.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
EXPOSE 8080
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "AccessControl.Api.dll"]